### PR TITLE
apiRoutes.js changes

### PR DESCRIPTION
**Pull request by prestonpatt**

### CODE REVIEW

**Comment by prestonpatt** [comment]
I don't think we care/need the index.js. They're all consts now instead of vars because I replaced them with something along the way.

**Review by Aaronjsmith0 — APPROVED** [review]
looks good to me

**Review by Aaronjsmith0 — APPROVED** [review]
good

**Comment by Aaronjsmith0** [comment]
it still has conflicts

**Comment by prestonpatt** [comment]
Nixing this one

**Pull request closed without merging**
